version: "3.7"

services:
    rails:
        container_name: "rails-container"
        build: 
            context: .
        volumes:
            - ./:/home/backend
        command: rails server -p 3000 -b 0.0.0.0
    
        ports: 
            - "3000:3000"
        depends_on: 
            - postgres
        networks:
            - database

    postgres:
        container_name: postgres-container
        image: library/postgres:9.6-alpine
        ports: 
            - "5431:5432"
        volumes: 
            - ./docker/postgres/data:/var/lib/postgresql/data
            - ./scripts/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
        environment:
            - POSTGRES_MULTIPLE_DATABASES=database,test
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root@123
        restart: always
        networks: 
            - database

    adminer:
        container_name: adminer-container
        image: adminer
        ports:
            - 8080:8080
        restart: always
        networks: 
            - database
 
networks:
  database:
    driver: "bridge"